//YOU WILL BE GIVEN EDGES FOR UNDIRECTED GRAPH IN THE INPUT.
//YOU HAVE TO FIND THAT IF THE GRAPH FORMED IS BIPARTIDE OR NOT.

//THE QUESTION CAN ALSO BE IN THE THE FORM THAT IS IT POSSIBLR TO DIVIDE THESE PEOPLE IN DIFFERENT GROUP.
//EACH INPUT WILL BE AN ARRAY OF SIZE 2 IN WHICH FIRST INDEX VALUE WILL BE FIRST PERSON AND SECOND INDEX VALUE
//WILL BE SECOND PERSON.

